mod build_binops;
mod build_cfg_to_ir;
mod build_dup;
mod build_globals;
mod build_io;
mod build_main;
mod build_not;
mod build_pointers;
mod build_pop;
mod build_push;
mod build_roll;
pub mod cfg_gen;
pub mod codegen;
mod consts;
mod print_stack;
pub mod settings;
