[package]
name = "piet-optimizer"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piet-interpreter = { version = "0.1", path = "../../interpreter" }
piet-core = { version = "0.1", path = "../../piet_core" }